# Generated by Django 4.2.6 on 2023-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0002_alter_stocks_stock_name_alter_stocks_stock_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
