# Generated by Django 5.1.2 on 2024-10-28 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_portfoliostock_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
