# Generated by Django 5.1.2 on 2024-10-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_portfoliostock_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostock',
            name='total_investment',
        ),
    ]
