# Generated by Django 5.1.2 on 2024-10-28 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_portfoliostock_total_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
